#######################################################
#################### DNS Changes ######################
#######################################################
---

- name: Set hostname
  command: "hostnamectl set-hostname {{inventory_hostname}}"

- name: Check hostname
  command: "hostname -f"
  register: hostname

#- name: Change the hostname to our standard
#  hostname:
#    name: "{{ inventory_hostname }}"
#  register: hostname

- debug: "msg={{ansible_nodename}}"

- name: Validate ansible_nodename == inventory_hostname
  tags:
    - validate
  assert:
    that:
      ansible_nodename == inventory_hostname
