---
- name: Install ROCK NSM /etc/issue
  copy:
    src: etc-issue.in
    dest: /etc/issue.in
    mode: 0644
    owner: root
    group: root

- name: NetworkManager ROCK NSM hook
  copy:
    src: nm-issue-update
    dest: /etc/NetworkManager/dispatcher.d/50-rocknsm-issue-update
    mode: 0755
    owner: root
    group: root