---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:
  vars:
    home_net:
      - "192.168.0.0/16"
      - "10.0.0.0/8"
      - "172.16.0.0/12"
    servicelastic_cidr: "192.168.1.16/28"
    bpf_filter: ""
    elastic_mem: 3
    elastic_masters: 4
    pcap_bpf_filter: ""
    elastic_datas: 0
    elastic_pv_size: 7
    kafka_pv_size: 1
    zookeeper_pv_size: 1
    zookeeper_replicas: 3
    pcap_pv_size: 0
    zookeeper_mem: 1
    kafka_mem: 1
    dns_ip:
    use_ceph_for_pcap: false

    moloch_spiDataMaxIndices: 5
    moloch_pcapWriteMethod: "simple"
    moloch_pcapWriteSize: 262143
    moloch_dbBulkSize: 300000
    moloch_maxESConns: 30
    moloch_maxESRequests: 500
    moloch_packetsPerPoll: 50000
    moloch_magicMode: "libmagic"
    moloch_maxPacketsInQueue: 200000
    pcap_folder: '/pcap'

  children:

    ceph:
      children:
        nodes:

    elasticsearch:
      children:
        nodes:

    logstash:
      children:
        elasticsearch:

    kibana:
      children:
        master-server:

    metricbeat:
      children:
        nodes:

    kafka:
      children:
        sensors:
        remote-sensors:

    bro:
      children:
        sensors:
        remote-sensors:

    moloch:
      children:
        sensors:
        remote-sensors:

    suricata:
      children:
        sensors:
        remote-sensors:

    # This role is not yet completed. Do not use.
    stenographer:

    # This role is not yet completed. Do not use.
    docket:

    nodes:

      children:

        sensors:
          hosts:
            rocksensor1.lan:
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 192.168.1.92
              bro_workers: 2
              monitor_interfaces:
              - ens34
              data_disk_devices:
              pcap_disk: /dev/sdb
              moloch_threads: 4
            rocksensor2.lan:
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 192.168.1.93
              bro_workers: 2
              monitor_interfaces:
              - ens224
              data_disk_devices:
              pcap_disk: /dev/sdb
              moloch_threads: 4

        remote-sensors:

        servers:

          hosts:
            rockserver2.lan:
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 192.168.1.91
              data_disk_devices:
              - /dev/sdb

        master-server:
          hosts:
            rockserver1.lan:
              ansible_user: root
              ansible_connection: ssh
              management_ipv4: 192.168.1.90
              data_disk_devices:
              - /dev/sdb
