# site.yml is the overall playbook, but all it does is include the other playbooks that are part of the site. For more
# information about the structure see:
# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html
# http://docs.ansible.com/ansible/latest/intro_inventory.html
# We follow the guidance to include naming conventions there.

---

- name: Configure Firewall
  hosts: all
  tasks:

    - name: Install beats
      command: "pkg add http://pkg.freebsd.org/FreeBSD:11:amd64/latest/All/beats-{{ elastic_version }}.txz"

    - name: Install required kernel modules
      copy:
        src: "{{ item }}"
        dest: /boot/kernel/
        owner: root
        group: wheel
        mode: 0555
      with_items:
        - LINPROCFS.KO
        - LINUX_COMMON.KO

    - name: Load Linux proc filesystem kernel module
      command: "kldload linprocfs.ko"

    - name: Verify compatibility modules are loaded
      command: kldstat
      register: kldstat

    - debug:
        msg: "{{ kldstat.stdout }}"

    - name: Create the directory to be used as the linux proc filesystem mount point
      file:
        path: "{{ linproc_mountpoint }}"
        state: directory
        owner: root
        group: wheel
        mode: 0755

    - name: Mount linproc file system
      mount:
        path: "{{ linproc_mountpoint }}"
        src: '/dev/null'
        state: mounted
        fstype: linprocfs

    - name: Mount linproc file system
      mount:
        path: "{{ linproc_mountpoint }}"
        src: '/dev/null'
        state: mounted
        fstype: linprocfs

    - name: Confirm linproc information is available
      command: 'ls /compat/linux/proc/'
      register: ls

    - debug:
        msg: "{{ ls.stdout }}"

    - name: Mount proc file system
      mount:
        path: "/proc"
        src: 'proc'
        state: mounted
        fstype: procfs

    - name: Confirm proc information is available
      command: 'ls /proc'
      register: ls

    - debug:
        msg: "{{ ls.stdout }}"

...
